# Generated by Django 4.1.7 on 2023-03-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0003_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
