# Generated by Django 4.1.7 on 2023-03-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fnacimiento',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
